// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dvqzltgyrrndyrndmclb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR2cXpsdGd5cnJuZHlybmRtY2xiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxMTY0NjQsImV4cCI6MjA1OTY5MjQ2NH0.HtNyj8bM4qjvEloDDPqZOAn0dANLQMaXdY4l0IgwWks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);